units:
  # Parameters
  # ==========
  kx: cx + 0.5    # Key spacing horizontal
  ky: cy + 0.5    # Key spacing vertical
  sf: 15          # Switch footprint (square)
  pinky_splay: 5  # Degrees of splay between pinky and ring columns
  ring_splay: 3   # Degrees of splay between ring and index columns
  visual_x: 1
  visual_y: 1

points.zones:

  # Key Switches
  # ============
  matrix:
    rotate: pinky_splay + ring_splay
    key: &key_attributes
      width: 18
      height: 17
      tags:
        key_switch: true
      footprints:
        - type: choc
          anchor:
            rotate: 180
          nets:
            from: GND
            to: =key_net
          params:
            reverse: true
            keycaps: true
    rows:
      bottom.padding: ky
      home.padding: ky
      top.padding: ky
    columns.pinky:
      spread: kx
      rows:
        top.key_net: P20
        home.key_net: P21
        bottom.skip: true
    columns.ring:
      spread: kx
      stagger: 2/3ky
      rotate: -pinky_splay
      rows:
        top.key_net: P14
        home.key_net: P16
        bottom.key_net: P10
    columns.middle:
      spread: kx
      stagger: 0.25ky
      rotate: -ring_splay
      rows:
        top.key_net: P19
        home.key_net: P18
        bottom.key_net: P15
    columns.index:
      spread: kx
      stagger: -0.25ky
      rows:
        top.key_net: P7
        home.key_net: P8
        bottom.key_net: P9
    columns.inner:
      spread: kx
      stagger: -0.5ky
      rows:
        top.key_net: P4
        home.key_net: P5
        bottom.skip: true
  thumb:
    key: *key_attributes
    anchor:
      ref: matrix_index_bottom
      shift: [0.25kx, -22]
    columns.tucky:
      key:
        name: thumb_tucky
        key_net: P6
    columns.reachy:
      spread: kx
      stagger: -0.25ky
      key:
        name: thumb_reachy
        key_net: P3

  # Outline Extents
  # ===================
  o_top_left:
    key:
      name: o_top_left
      height: 0
      width: 0
    anchor:
    - ref: matrix_middle_top
      shift: [0, 0.5sf]
    - ref: matrix_pinky_home
      affect: x
      shift: [-0.75sf, 0]
  o_top_right:
    key:
      name: o_top_right
      height: 0
      width: 0
    anchor:
    - ref: o_top_left
    - ref: thumb_reachy
      affect: x
      shift: [0.5sf, 0]
  o_bottom_left:
    key:
      name: o_bottom_left
      height: 0
      width: 0      
    anchor:
    - ref: o_top_left
    - ref: thumb_reachy
      affect: y
      shift: [0, -0.5sf]
  o_bottom_right:
    key:
      name: o_bottom_right
      height: 0
      width: 0      
    anchor:
    - ref: o_top_right
    - ref: o_bottom_left
      affect: y

  # Footprint Positions
  # ===================
  mcu:
    key:
      name: mcu
      height: &mcu_h 18
      width: &mcu_w 33
    anchor:
      - ref: o_bottom_left
        shift: [17.5, 0]
      - ref: thumb_tucky
        affect: y
  power_jumper:
    key:
      name: power_jumper
      height: &power_jumper_h 4.4
      width: &power_jumper_w 1.8  
    anchor:
      - ref: matrix_ring_bottom
        shift: [6, 0]
        rotate: -ring_splay + 90
      - ref: thumb_tucky
        shift: [0, -0.5ky + 3]
        affect: y
  battery_pads:
    key:
      name: battery_pads
      height: &battery_pads_h 2.1
      width: &battery_pads_w 3.8
    anchor:
      - ref: o_bottom_left
        shift: [*mcu_w, 0]
      - shift: [5, 0]
      - ref: thumb_tucky
        shift: [0, 0.5ky - 1]
        affect: y
  reset:
    key:
      name: reset
      height: &reset_h 3.8
      width: &reset_w 2.1
    anchor:
    - ref: o_bottom_left
      shift: [*reset_w, *mcu_h]
      rotate: 90
    - shift: [0, 6]

outlines.exports:
  _outer:
    - type: polygon
      points:
      - ref: o_top_left
      - ref: o_top_right
      - ref: o_bottom_right
      - ref: o_bottom_left
  _panel:
    - name: _outer
      fillet: 3
  total_demo:
    - _panel
pcbs:
  berylline:
    outlines:
      main:
        outline: _panel
    footprints:
      - type: promicro
        anchor.ref: mcu
        params:
          orientation: up
      - type: jumper
        anchor.ref: power_jumper
        nets:
          from: RAW
          to: RAW
      - type: jumper
        anchor.ref: battery_pads
        nets:
          from: RAW
          to: GND
      - type: jumper
        anchor.ref: reset
        nets:
          from: RST
          to: GND
